SET NAMES utf8;

DROP DATABASE IF EXISTS project_dw;

CREATE DATABASE IF NOT EXISTS project_dw DEFAULT CHARACTER SET utf8;

USE project_dw;

DROP TABLE IF EXISTS dim_location;
DROP TABLE IF EXISTS dim_time;
DROP TABLE IF EXISTS fact_table;

CREATE TABLE dim_location (
    LOCATION_ID INT PRIMARY KEY,
    CITY VARCHAR(50),
    DISTRICT VARCHAR(50),
    COUNTY VARCHAR(50)
)

CREATE TABLE dim_time (
    TIME_ID INT PRIMARY KEY,
    YEAR INT,
    MONTH VARCHAR(20),
    DAY INT
)

CREATE TABLE fact_table (
    PRICE INT,
    LOCATION_ID INT,
    TIME_ID INT,
    PRIMARY KEY (LOCATION_ID, TIME_ID),
    FOREIGN KEY (LOCATION_ID) INT REFERENCES dim_location(LOCATION_ID),
    FOREIGN KEY (TIME_ID) INT REFERENCES dim_time(TIME_ID)
)
