SET NAMES utf8;

DROP DATABASE IF EXISTS project_dw;

CREATE DATABASE IF NOT EXISTS project_dw DEFAULT CHARACTER SET utf8;

USE project_dw;

DROP TABLE IF EXISTS dim_location;
DROP TABLE IF EXISTS dim_time;
DROP TABLE IF EXISTS fact_table;

CREATE TABLE dim_location (
    LOCATION_ID INT PRIMARY KEY AUTO_INCREMENT,
    POSTCODE VARCHAR(8),
    STREET VARCHAR(50),
    PAON VARCHAR(100),
    SAON VARCHAR(100),
    LOCALITY VARCHAR(100),
    CITY VARCHAR(50),
    DISTRICT VARCHAR(50),
    COUNTY VARCHAR(50)
);

CREATE TABLE dim_time (
    TIME_ID DATE PRIMARY KEY,
    YEAR_ID INT,
    MONTH_ID VARCHAR(40),
    DAY_ID INT
);

CREATE TABLE fact_table (
    PRICE INT,
    LOCATION_ID INT,
    TIME_ID DATE,
    PRIMARY KEY (LOCATION_ID, TIME_ID),
    FOREIGN KEY (LOCATION_ID) REFERENCES dim_location(LOCATION_ID),
    FOREIGN KEY (TIME_ID) REFERENCES dim_time(TIME_ID)
);
